### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by oniz93** [jackdh/RasaTalk#10]
Hi,
those are the steps that I did:
- setup Rasa Core (0.12.2) and Rasa NLU (0.13.8) in the same docker, exposing on ports 5000 (NLU) and 5005 (Core)
- setup RasaTalk with a local MongoDB and pointing Rasa NLU;
- created an Agent with a couple of intents inside;
- created a Flow with a couple of nodes;
- trained Rasa with those infos;

After doing all those steps, I try to talk with the integrated Chatbot for each message I send I receive a "Sorry something went wrong".

What I'm doing wrong?

Where I can find the files to train Rasa Core (stories.md & domain.yml)? 
Does RasaTalk create them like RasaUI?

Thank you so much

**Comment by jackdh** [comment]
Hey @oniz93 

Sorry about that! I've pushed a fix! I quickly added a caching mechanisim yesterday and forgot to run a test! Two darn `{ }` caused the issue!

In future if you'd like to know why if you add `DEBUG=*` to the .env file it will print out any error messages! Please let me know if that fixed the first mistake!

I've not yet added stories for Rasa Core just yet but it's in the pipeline!

**Comment by jackdh** [comment]
Hey @oniz93 

I'm going to assume this is fixed up now so will close this! Please feel free to reopen it if it break again!
