### ISSUE TITLE
Dont Connect to Rasa

### ISSUE THREAD

**Issue by igorgadelha** [jackdh/RasaTalk#11]
Hello,
I've been trying for three days and I have not been successful yet. :/

Always on startup, its not connect to mongo db (I will tested with local, mongo in docker and mlab), showing:

rasatalk_1  | MongoDB connection FAILED. It is required to register / login error: failed to connect to server [192.168.0.7:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 192.168.0.7:27017]
mongo       | 2018-12-19T13:20:48.343+0000 I STORAGE  [initandlisten] WiredTiger message [1545225648:343823][1:0x7f3c2908ca40], txn-recover: Set global recovery timestamp: 0
mongo       | 2018-12-19T13:20:48.358+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongo       | 2018-12-19T13:20:48.417+0000 I CONTROL  [initandlisten] 
mongo       | 2018-12-19T13:20:48.418+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo       | 2018-12-19T13:20:48.419+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo       | 2018-12-19T13:20:48.421+0000 I CONTROL  [initandlisten] 
mongo       | 2018-12-19T13:20:48.428+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: ef351971-04f7-406a-bd25-a5752108fe10
mongo       | 2018-12-19T13:20:48.489+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.0
mongo       | 2018-12-19T13:20:48.507+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 2a136f2a-b9ae-4f08-87f2-89f9f63ece0f
mongo       | 2018-12-19T13:20:48.556+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo       | 2018-12-19T13:20:48.565+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
mongo       | 2018-12-19T13:20:48.569+0000 I STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with generated UUID: 42a091ed-ece9-446d-9368-ecdde8696fad
mongo       | 2018-12-19T13:20:48.653+0000 I INDEX    [LogicalSessionCacheRefresh] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
mongo       | 2018-12-19T13:20:48.655+0000 I INDEX    [LogicalSessionCacheRefresh] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo       | 2018-12-19T13:20:48.666+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
mongo       | 2018-12-19T13:20:48.669+0000 I COMMAND  [LogicalSessionCacheRefresh] command config.$cmd command: createIndexes { createIndexes: "system.sessions", indexes: [ { key: { lastUse: 1 }, name: "lsidTTLIndex", expireAfterSeconds: 1800 } ], $db: "config" } numYields:0 reslen:114 locks:{ Global: { acquireCount: { r: 2, w: 2 } }, Database: { acquireCount: { w: 2, W: 1 } }, Collection: { acquireCount: { w: 2 } } } protocol:op_msg 101ms

 another problem is the rasa not connect in any time (in yarn or docker startups)

How to solve it ?
 i start the with docker-compose up.
in two times the auth is working,
register user, 
create a agent and  always showing the message "rasa not connect".

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser chrome, firefox developer edition, safari.
 
thanks for all support

**Comment by jackdh** [comment]
Interesting,

Could you please try without docker-compose if that is an option for you?

Please also can you confirm that you can connect to Mongodb from the same location that you are trying to run the docker-compose from please

**Comment by jackdh** [comment]
Hey I just copied your log to a gist file so it's a bit more readable.

Okay so I just tried doing a fresh install on a mac as well. Please can you follow these steps to make sure its running:

First update yarn

1. `sudo yarn install`
2. Set up Rasa
  2.1 Then go to http://yoursever:5000 and make sure you get "hello from Rasa NLU: 0.****"
3. Set up Mongo
  3.1 Then go to http://yoursever:27017 and make sure you get "hello from Rasa NLU: 0.****"
4. make sure you create a `.env` file and it looks like this:

```
ENABLE_TUNNEL=false
NODE_ENV=development
PORT=5001
RASASERVER=http://YOURRASASERVER:5000
JWTSECRET=62make_sure_to_change_this1
MONGOCONNECTIONSTRING=mongodb://YOURMONGOSERVER27017/rasa-talk-local
MONGOUSER=
MONGOPASS=
```
Then please try connecting and let me know what happens!

If still nothing please send me your IP and I will whitelist you to my server so we can test using my Rasa / Mongo if you wish.

**Comment by igorgadelha** [comment]
its Works! Thanks  @jackdh !! :)

**Comment by jackdh** [comment]
Glad to heara @igorgadelha! Did you find what the particular issue was?
