### ISSUE TITLE
While Adding Working flow conditions

### ISSUE THREAD

**Issue by gowtham4gs** [jackdh/RasaTalk#14]
/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

**Comment by gowtham4gs** [comment]
resolve the error to reinstalled the packaged . do you have any guide for all functionality configurations. like slot,workflow.,.etc please share to gowthaman.cse@live.com

**Comment by jackdh** [comment]
Glad to hear the error is resolved.

I've written up some of the details on the wiki page but just haven't had the time to add all the information just yet.

Slots will basically try and exact any found slot from the sentence (you can test it by sending the sentence to Rasa and see the returned slots) then save them in a variable which you can then use in webhooks / responses / next replies.

The workflow works like a waterfall, when you enter the top on in that session it is then possible to trigger the ones below it and so on. This will reset on a session change.,
