### ISSUE TITLE
It is not going any further

### ISSUE THREAD

**Issue by Ajinkz** [jackdh/RasaTalk#16]
**Describe the bug**
VirtualBox:~/RasaTalk$ yarn
yarn install v1.13.0
$ npm run npmcheckversion
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1550479431722-0.303340767008462/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> rasa-talk@1.1.0 npmcheckversion /home/ajinkz/RasaTalk
> node ./internals/scripts/npmcheckversion.js

[1/5] Validating package.json...
[2/5] Resolving packages...
⢀ lodash@>=4.17.11^Z

**Screenshots**
![image](https://user-images.githubusercontent.com/11535456/52938657-35a3b200-3388-11e9-9419-6c8e61862c8c.png)

**Desktop (please complete the following information):**
 - OS: 16.04
 - Browser Firefox
 - Version 65.0

**Comment by jackdh** [comment]
What version of NPM are you running?

Can you try running `yarn install` instead?

**Comment by Ajinkz** [comment]
![image](https://user-images.githubusercontent.com/11535456/52967878-8e4b6d00-33d1-11e9-95c3-d74299d05f61.png)

**Comment by jackdh** [comment]
It looks like yarn in not properly installed.

Maybe just use NPM instead.

So `npm install`

**Comment by jackdh** [comment]
Hey @Ajinkz Please reopen this if the error reoccurs.
