### ISSUE TITLE
Slot

### ISSUE THREAD

**Issue by gowtham4gs** [jackdh/RasaTalk#17]
Jackdh,
kindly give guide for slot filling configuration with rasa talk GUI. give any gif or document for this

thanks

**Comment by jackdh** [comment]
Hi,

Gow sure I will try when I have time!

**Comment by gowtham4gs** [comment]
thanks for quick reply jackdh, i am waiting for your reply and i'm trying my side also

**Comment by gowtham4gs** [comment]
need clarify for  [number] and [topping] in your hosted reference image.how to do i configure for this.

thanks

**Comment by jackdh** [comment]
Ah okay.

So first step is to create the entities here:

https://talk.jackdh.com/entities/pizza_topping


Then you will need to create some training data which uses those entities.

As you can see here:

https://talk.jackdh.com/agents/ag-Pizza/intent/order_pizza_test

Then when you train it run for instance this command

"I would like a pizza please"

You will see the word "pizza being extracted as the food type"

![image](https://user-images.githubusercontent.com/1907451/53028116-2bec7e00-345e-11e9-8c12-976ba3b78ff7.png)

**Comment by jackdh** [comment]
Then in the talk section you can look for and save the that entity as whatever you wish. In my instance I chose [food] (*this has changed to food from toppings since that original photo*) then you can use [food] in the reply.

**Comment by gowtham4gs** [comment]
Jackdh,
Wow i got amazing updating in your dashboard, related to pizza. i'm so exciting i hope you going to update talkGroups also for pizza slot filling.... 


Thanks

**Comment by gowtham4gs** [comment]
Jackdh,,
You using so much techniques  like
 1.Looks for
2.save it as,
3.default value
 can you say the  purpose of the features. 
and input formats ...

Thanks

**Comment by jackdh** [comment]
Sure!

**Look For**
This is the name of the entity to look for, eg "food" (from above picture)

**Save it as**
This is the name you will save it as so you can use it later in a reply. For instance you would save it as [the_users_food_choice] then you can have a reply which is:

`You have ordered a: [the_users_food_choice]!`

This would output to the user as:

`You have ordered a pizza!`

**Prompt**
So a prompt will only be used is the below **Is it Required?** is set to **True**.

For instance if the prompt was "What food"? and the user did not specify some food like "can I order something"

the bot would reply with:

`What food?`

**Is it Required?**
This is used to chose between the default value or a prompt

**Default Value**
If the slot is not required, you can add in a default value. For instance if the default was "chocolate" and the user said `can I order something` the response would be:


`You have ordered a chocolate!`

Does this help? I will write this up in the wiki when I get a chance!

**Comment by gowtham4gs** [comment]
Sure thanks alot jackdh...

**Comment by gowtham4gs** [comment]
Hi jackdh,
I need clarification about group name in node section.and web hook config....
 Your every guidelines so helpful and very understanding.
Thanks...

**Comment by gowtham4gs** [comment]
Thanks for quick reply,
i have configured webhook in post method but not ,posting the method, and i have another doubt in slot ,
possible to send slot values via webhooks.

**Comment by jackdh** [comment]
Yes and No.

I've added it but it's still locally done I'm afraid I've not pushed it out to git. I'll try and do that this weekend if I have time.

Otherwise you can get hacking and include them from the stored session object!

**Comment by gowtham4gs** [comment]
Ok eagerly I'm waiting jack ...if u have any screen shot can u show me

**Comment by gowtham4gs** [comment]
Related to webhook

**Comment by gowtham4gs** [comment]
You have added in your page webhook yes or no option but I'm not aware about configuration in that kindly do the needful.im so struggling in that socket calling in get/post method

**Comment by jackdh** [comment]
I'm at work currently so can't look right now. I know the slots work in the get / post as I am using it at home. However I may not have pushed it to the repository just yet.

**Comment by gowtham4gs** [comment]
thanks for your quick response, if you got a time kindly explain about web hook,group name,save user response in node section and prompt in slot section.

-THANKS
