### ISSUE TITLE
SLOT prompt

### ISSUE THREAD

**Issue by gowtham4gs** [jackdh/RasaTalk#18]
i have configured slot,but not working prompt and child node slot not working for me

**Comment by jackdh** [comment]
Hey @gowtham4gs please can you fill out the issue with more details like they are requested otherwise it is nigh on impossible to help!

I'll reopen then it's updated!

**Comment by gowtham4gs** [comment]
Hi Jackdaw,
Thanks for your response...

1) slot filling prompt not working for me.
Ex. 
`food`  `[foodtype]` `what food youlike?` 
above input filled in slot values are stored but .prompt not coming. &

2) I have configured webhook like below but not working:

i have created one POST api,(api return something as per the input)

`http://127.0.0.1:5001/api/result`    `POST`       `{"data":"hi"}`

success id    failure id
this function also i made some mistake but don't know where
3)is it possible to send slot or rasa engine json value via webhook

Thanks for your support. 
Jackdh

**Comment by gowtham4gs** [comment]
Hi jackdh,
I'm very struggling in this..I'm tried lot of ways can u get free time do the needful..
Thanks

**Comment by gowtham4gs** [comment]
Thanks for your support....:smile:
