### ISSUE TITLE
how to config environment file on windows and how to get jwt secret token? is it necessary ??

### ISSUE THREAD

**Issue by Ajinkz** [jackdh/RasaTalk#19]
`

      Mongo: undefined ✓
      Rasa: undefined
      Localhost: http://localhost:3000
      LAN: http://192.168.137.1:3000

`
MongoDB connection FAILED. It is required to register / login error: URL malformed, cannot be parsed`

**My .env file**

```
ENABLE_TUNNEL=false
NODE_ENV=development
PORT=5001
RASASERVER=http://localhost:5000
MONGOCONNECTIONSTRING=mongodb://localhost:27017/rasalog
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11535456/53620871-82a24680-3c1a-11e9-87ff-010755466f31.png)

 - OS: window 10
 - Browser: Firefox

**Comment by jackdh** [comment]
It looks like it cannot find your mongodb instance, is it running / you can connect to it?

I run this mainly on windows so I know it's working,

**Comment by jackdh** [comment]
Actually saying undefeined it looks like it's not even loaded the `.env` file.

Can you show me what your folder structure looks like?
