### ISSUE TITLE
 how to open existing rasa nlu/domain files in rasatalk ? #20 

### ISSUE THREAD

**Issue by Ajinkz** [jackdh/RasaTalk#21]
**Describe the bug**
I already have my rasa model ready and working. How to open those files in 
RasaTalk? or How can I import files of existing models instead of creating a new one?

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser : Firefox
 - Version 65.0

**Comment by jackdh** [comment]
This isn't really a bug @Ajinkz 

If you're model is already working in rasa then when you point rasa talk to your Rasa NLU server it will populate it within Rasa Talk.

Rasa Talk does not host the Rasa NLU models that is done within the docker container or whereever you are hosting your Rasa NLU.
