### ISSUE TITLE
Help needed - version of Rasa NLU/core

### ISSUE THREAD

**Issue by RochaCarla** [jackdh/RasaTalk#22]
Rasa is constantly updating its nlu+core version. The docker-compose does not specify which version of rasa is used ( image: rasa/rasa_nlu ). Therefore, rasatalk is not working with the latest version. Can you specify which version are you using?

**Comment by gowtham4gs** [comment]
if possible to connect mysql database instead of mongo?

**Comment by jackdh** [comment]
Hey @RochaCarla 

Sorry for the late reply. I was using Rasa NLU version 13.2 however if it is no longer working for the most recent release I will attempt to patch it!

Thanks,

**Comment by RochaCarla** [comment]
Thanks! I'll try it
