### ISSUE TITLE
if possible to connect mysql database instead of mongo?

### ISSUE THREAD

**Issue by gowtham4gs** [jackdh/RasaTalk#23]
i want connect with mysql data base instead mongo db is it possible?

**Comment by jackdh** [comment]
No sorry, it currently only supports MongoDB.

**Comment by gowtham4gs** [comment]
your preferring no sql db only correct, and its support other than mongo db.

**Comment by jackdh** [comment]
Currently it only supports MongoDB. It might be possible to write a new database layer to extract it and use SQL.
