### ISSUE TITLE
Rasa NLU gives permissions error

### ISSUE THREAD

**Issue by sameerg07** [jackdh/RasaTalk#27]
`rasatalk_1  |         ServerResponse: [Function],
rasatalk_1  |         createServer: [Function: createServer],
rasatalk_1  |         get: [Function: get],
rasatalk_1  |         request: [Function: request],
rasatalk_1  |         maxHeaderSize: [Getter] },
rasatalk_1  |      'https:':
rasatalk_1  |       { Agent: [Function],
rasatalk_1  |         globalAgent: [Agent],
rasatalk_1  |         Server: [Function],
rasatalk_1  |         createServer: [Function: createServer],
rasatalk_1  |         get: [Function: get],
rasatalk_1  |         request: [Function: request] } } }
rasatalk_1  | 2019-04-08T08:36:04.874Z Training Error: connect ECONNREFUSED 127.0.0.1:5000`

**Comment by jackdh** [comment]
Hey @sameerg07 Please provide all the requested information when opening an issue as I can't help with just this output.

**Comment by sameerg07** [comment]
I ran the rasa nlu server and then when I go to train the agent, it shows this error saying that /api/train isnt allowed.

**Comment by jackdh** [comment]
Have you tried training the model with just some dummy information from the Rasa NLU website?
