### ISSUE TITLE
Slots aren't being prompted.

### ISSUE THREAD

**Issue by sameerg07** [jackdh/RasaTalk#30]
Can we have a good documentation on how can we use the interface, specific to each and every part of the UI. 
Slot isnt prompted.
![image](https://user-images.githubusercontent.com/22883918/56565856-f33c6280-65ce-11e9-8b33-931646bb2313.png)

**Comment by sameerg07** [comment]
Any updates?

**Comment by jimil24111990** [comment]
I have the same issue. Any update on this would help.

**Comment by jackdh** [comment]
Hey @sameerg07 @jimil24111990 

Sorry I'm been just swamped at work. Anyway for somereason it looks like the foreach loop's where breaking (Absolutely no idea why if anyone know that would be really interesting!)

Anyway I updated them to use good old for i loops and they seem to be working now:

Commit: https://github.com/jackdh/RasaTalk/commit/07f4e6052f65b5c2eaf41cd827dafc25e9339aa0

![image](https://user-images.githubusercontent.com/1907451/59135397-ab9f4980-8976-11e9-8ec6-9756bfbd2067.png)
