### ISSUE TITLE
Edit Entity?

### ISSUE THREAD

**Issue by TaraRavindra** [jackdh/RasaTalk#31]
How to edit an entity?

**Comment by jackdh** [comment]
Please see here:

https://github.com/jackdh/RasaTalk/wiki/Creating-Training-Data

**Comment by TaraRavindra** [comment]
Jack, the link u sent tells me how to configure. I need to know if editing the name of an already created entity is possible? Eg: Entity name: Weather, has multiple expressions under it. I want to change the name to Ask_Weather. Is the Possible Jack?

**Comment by jackdh** [comment]
@TaraRavindra Sorry just seen this you should have reopened it!

Yes you can rename it.
No cannot do it via the UI.

To rename it you will need to edit it in the database in the following places:

In the entities Database:
https://i.imgur.com/vkHMM0L.png

In each place it is referenced in the training data
https://i.imgur.com/h0msEvC.png

it's a bit crap and would love to add a way in the UI to do it automatically.
