### ISSUE TITLE
RASASERVER can't conect

### ISSUE THREAD

**Issue by lfernando2091** [jackdh/RasaTalk#36]
**Describe the bug**
I can't conect to my RASA server and log doesn't shows why.

**To Reproduce**
1. I change the env RASASERVER to my ip direction server
2. I started the project
3. The log shows all works well.
4. When I login on my dashboard, it shows error to conect RASA

**Expected behavior**
To start used RASA Talk

**Screenshots**
![image](https://user-images.githubusercontent.com/23199936/66610752-3476fd80-eb82-11e9-99f0-471c0b2b0733.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10
 - Browser CHROME

**Comment by amantyatech** [comment]
Same issue, also Rasa NLU server require a model to start which is not there. What model file to place here

**Comment by rishi454** [comment]
same issue. how to solve this issue.

**Comment by bharath1210** [comment]
i had also a same issue can anyone say while model need to be added and how to fix it

**Comment by jackdh** [comment]
Hi sorry for the really late reply.

Can you access the rasa server if you pinged it directly? First step to debug this is to make sure rasa is up and running on it's own / connectable.

**Comment by abhishekagg2604** [comment]
Same issue, can't connect to rasa.

**Comment by niveditapdixit** [comment]
Hi , 
Can someone please respond if they were able to resolve the issue mentioned above. My rasa server is up and validate it by the on the browser and it  returns valid response , hence the rasa server is up, but  in rasa talk it shows as the rasa server is down . Can you pls help resolve the issue. The configurations in .env are pointing to correct URL of the local rasa server

**Comment by muthukumars** [comment]
same issue

**Comment by shreeraj04** [comment]
Same Issue with rasa v1.10

**Comment by amm297** [comment]
Hi, some news on this?

**Comment by lfernando2091** [comment]
Due inactivity :(
