### ISSUE TITLE
Error!!!!!!

### ISSUE THREAD

**Issue by Cesarcuna** [jackdh/RasaTalk#37]
![995f46a5-0490-4a54-9764-3a8139f59894](https://user-images.githubusercontent.com/30168143/66614434-ad7c5200-eb8e-11e9-911b-0f682c8bcb00.jpg)

![4186609a-75f3-4cde-b8b6-48d6a58180fb](https://user-images.githubusercontent.com/30168143/66614443-b40ac980-eb8e-11e9-9951-fef11756433d.jpg)

![image](https://user-images.githubusercontent.com/30168143/66614462-c258e580-eb8e-11e9-8774-501d6429e76d.png)

**Comment by jackdh** [comment]
The NPM install errors are expected fails due to sharing of modules between the frontend and backend.

The Errors after it looks like you've it's failed to build.

Can you please send me the steps you used to get to this position?

**Comment by jackdh** [comment]
Closing for stale, please reopen with the provided details if required!
