### ISSUE TITLE
where is the environment file and how to configure it?

### ISSUE THREAD

**Issue by zhaoyueplc** [jackdh/RasaTalk#6]
Hi ,
The error pops up:Please check environment file ,no port /JWT/MONGO/....specified,when the code ran.

It might be the environment file issue:
logger.error('Please check environment file.');
if (!process.env.PORT) logger.error('No port specified');
if (!process.env.RASASERVER) logger.error('No Rasa ip specified');
if (!process.env.JWTSECRET) logger.error('No JWT Secret specified');
if (!process.env.MONGOCONNECTIONSTRING) logger.error('No Mongo specified');
debug('Please update the .env file');

Would you like show me the environment file for the reference?

**Comment by jackdh** [comment]
Hi Zhaoyueplc,

What is the location of your environment file / how are you loading it in?

I currently load it in like so:

![webstorm64_2018-08-08_08-53-25](https://user-images.githubusercontent.com/1907451/43823945-9a75884a-9ae8-11e8-9e8b-fe2849923a6d.png)

However you can include the environment variables on the startup of the server like:

`PORT=8080 RASASERVER=etc node server`

Thank you for pointing out the missing .env example file I'll include that now.
