### ISSUE TITLE
Module not found: Error: Can't resolve

### ISSUE THREAD

**Issue by ctrado18** [jackdh/RasaTalk#7]
I get many errors like:

```
ERROR in ./node_modules/destroy/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\RasaTalk\node_modules\destroy'
 @ ./node_modules/destroy/index.js 14:17-30
 @ ./node_modules/send/index.js
 @ ./node_modules/serve-static/index.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./node_modules/botkit/lib/CoreBot.js
 @ ./node_modules/botkit/lib/Botkit.js
 @ dll reactBoilerplateDeps
```
on windows with yarn 1.7

**Comment by jackdh** [comment]
Hi @ctrado18 this looks like an error install node_modules.

Can I suggest you delete the node_modules and both `package-lock.json` |  `yarn.lock` (if they exist) and reinstall with `yarn install` or `npm install`

**Comment by ctrado18** [comment]
I followed your suggestion and tried both commands to install. But still same issue!

**Comment by jackdh** [comment]
Ah I recognise this. So it's not actually an error and it will run fine. This error occurs due to running both frontend and backend modules from one package.json

Currently on mobile however I'll try and find the link to why in the morning!

In the mean time it should work perfectly fine with the warnings!

**Comment by ctrado18** [comment]
Ok, with yarn start I get:

```
yarn run v1.7.0
$ cross-env NODE_ENV=development node server
Please check environment file.
No port specified
No Rasa ip specified
No JWT Secret specified
No Mongo specified

C:\Users\RasaTalk\node_modules\mongoose\lib\connection.js:424
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at new MongooseError (C:\Users\RasaTalk\node_modules\mongoose\lib\error\mongooseError.js:11:11)
    at NativeConnection.Connection.openUri (C:\Users\RasaTalk\node_modules\mongoose\lib\connection.js:424:11)
    at Mongoose.connect (C:\Users\RasaTalk\node_modules\mongoose\lib\index.js:230:15)
    at Object.<anonymous> (C:\Users\RasaTalk\server\mongo\schemas\chatbot_db_connect.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\RasaTalk\server\authentication\models\user.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But I thinki just have to include the variables now?

**Comment by jackdh** [comment]
Yup exactly, take a look at `example.env`, update that and rename it to `.env` and you should be good to go!

**Comment by ctrado18** [comment]
It works now! But do really have to register a new user? Why is that? And it says:

`info: ** No persistent storage method specified! Data may be lost when process shuts down.`

**Comment by ctrado18** [comment]
registration don't work! It takes long time until it stops sending the registration formular!

**Comment by jackdh** [comment]
Sounds like you've not hooked up a mongoDB instance. Are you running it locally or an online one? The registration can be removed if you want it to.

**Comment by ctrado18** [comment]
Thanks!

> Sounds like you've not hooked up a mongoDB instance. Are you running it locally or an online one? 

What you mean? I created an account on mlab for Mongo and typed the URi, not more?!

>The registration can be removed if you want it to.

How?

**Comment by jackdh** [comment]
Ah I've not tested it with an online MongoDB instance before as this was primarily built to be on premise so I used a local version. However it should not really matter if it's online. I'll give it ago after work.

As for removing registration you can rename `PrivateRoute` to `Route` here: https://github.com/jackdh/RasaTalk/blob/95e544a8445d25680047980e37a7e82b1afc5397/app/containers/App/index.js#L58

That should allow you to bypass authentication for logging in.

Then you can change https://github.com/jackdh/RasaTalk/blob/95e544a8445d25680047980e37a7e82b1afc5397/server/authentication/guard.js#L10

to `if (true)`

**Comment by jackdh** [comment]
Hey @ctrado18 , I'm going to close this now. Please feel free to message me on gitter if you want to continue any troubleshooting questions!
