### ISSUE TITLE
Remove Login request page

### ISSUE THREAD

**Issue by ctrado18** [jackdh/RasaTalk#9]
I followed the steps mentioned here: https://github.com/jackdh/RasaTalk/issues/7#issuecomment-412575343

But still I get redirected immediately to the login-page. How can I remove this since I cannot register...

**Comment by jackdh** [comment]
Hey @ctrado18 is there a particular reason you want to remove the login / authentication?

Can you try pulling the latest version and if you are using MongoDB add in the new environmental fields for MONGOUSER / MONGOPASS ?

**Comment by jackdh** [comment]
Any luck @ctrado18 ?

**Comment by jackdh** [comment]
I'm going to close this issue now as it's been a week @ctrado18 with no reply. Thanks!
